template_path: "remote/transit-gateway-attachment.yaml"
stack_name: "sage-tgw-sandcastlevpc"
dependencies:
  - "prod/sandcastlevpc.yaml"
parameters:
  VpcName: "sandcastlevpc"
  TransitGatewayId: 'tgw-08aa3c487e457374a'   # sage-tgw transit gateway
hooks:
  before_launch:
    - !cmd "curl https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/aws-infra/master/transit-gateway-attachment.yaml --create-dirs -o templates/remote/transit-gateway-attachment.yaml"
