template_path: "remote/sc-portfolio-ec2.yaml"
stack_name: "sc-portfolio-ec2"
dependencies:
  - "prod/sc-ec2vpc-launchrole.yaml"
  - "prod/sc-enduser-iam.yaml"
parameters:
  LaunchRoleName: "SCEC2LaunchRole"
  PrincipalRoleName1: "ServiceCatalogEndusers"
  PrincipalGroupName1: "ServiceCatalogEndusers"
  RepoRootURL: "https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/scipoolprod-sc-lib-infra/master/"
  StackDatetime: !date
hooks:
  before_launch:
    - !cmd "curl https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/scipoolprod-sc-lib-infra/master/ec2/sc-portfolio-ec2.yaml --create-dirs -o templates/remote/sc-portfolio-ec2.yaml"
